export const Images = {
  logo: require('./images/LogoBG.png'),
  waves: require('./images/waves.png'),
  land1: require('./images/land1.png'),
  land2: require('./images/land2.png'),
  profileicon: require('./images/profileicon.png'),
  scanner: require('./images/scanner.png'),
  secure: require('./images/secure.png'),
  assets: require('./images/assets.png'),
  explore: require('./images/explore.png'),
  home: require('./images/home.png'),
  trade: require('./images/trade.png'),
  down:require('./images/down.png'),
  buy : require('./images/buy.png'),
  earn : require('./images/earn.png'),
  recieve : require('./images/recieve.png'),
  send : require('./images/send.png'),
  coinlogo : require('./images/coinlogo.png'),
  tradelogo : require('./images/trade.png'),
  pros: require('./images/pros.png'),
  cross:require('./images/cross.png'),
  projects: require('./images/Projectsmain.png'),
  projectlogo: require('./images/projectlogo.png'),
  list1: require('./images/list1.png'),
  list2: require('./images/list2.png'),
  list3: require('./images/list3.png'),
  list4: require('./images/list4.png'),
  list5: require('./images/list5.png'),
  list6: require('./images/list6.png'),
  backscreen: require('./images/backscreen.png'),
  comment: require('./images/comment.png'),
  prosimage: require('./images/prosimage.png'),
  crossoverlay: require('./images/closeoverlay.png'),
  primary: require('./images/primary.png'),
  primary1: require('./images/primary1.png'),
  primary2: require('./images/primary2.png')
}
